spring:
  datasource:
    url: jdbc:mysql://localhost:3307/poc_users_db
    username: poc_users
    password: poc_users_pass

server:
  port: 8080
  
security:
  jwt.secret: palabrasecreta

  jwt.issuer: Main

  jwt.ttlMillis: 10800000